{{ config(
    materialized = 'view',
    persist_docs ={ "relation": true,
    "columns": true }
) }}

SELECT
    block_number,
    hash as block_hash,
    block_timestamp,
    'mainnet' AS network,
    tx_count,
    SIZE,
    miner,
    extra_data,
    parent_hash,
    gas_used,
    gas_limit,
    base_fee_per_gas,
    difficulty,
    total_difficulty,
    sha3_uncles,
    uncles as uncle_blocks,
    nonce,
    receipts_root,
    state_root,
    transactions_root,
    logs_bloom,
    blocks_id AS fact_blocks_id,
    inserted_timestamp,
    modified_timestamp,
    OBJECT_CONSTRUCT(
        'baseFeePerGas',
        base_fee_per_gas,
        'difficulty',
        difficulty,
        'extraData',
        extra_data,
        'gasLimit',
        gas_limit,
        'gasUsed',
        gas_used,
        'hash',
        HASH,
        'logsBloom',
        logs_bloom,
        'miner',
        miner,
        'nonce',
        nonce,
        'number',
        NUMBER,
        'parentHash',
        parent_hash,
        'receiptsRoot',
        receipts_root,
        'sha3Uncles',
        sha3_uncles,
        'size',
        SIZE,
        'stateRoot',
        state_root,
        'timestamp',
        block_timestamp,
        'totalDifficulty',
        total_difficulty,
        'transactionsRoot',
        transactions_root,
        'uncles',
        uncles
    ) AS block_header_json,
    'sei' AS blockchain -- deprecate
FROM
    {{ ref('silver_evm__blocks') }}
