name: dbt_run_scheduled_lq_load
run-name: dbt_run_scheduled_lq_load

on:
  workflow_dispatch:
  schedule:
    # “Every 15 minutes”
    - cron: '3,13,23,33,43,53 * * * *'

env:
  USE_VARS: "${{ vars.USE_VARS }}"
  DBT_PROFILES_DIR: "${{ vars.DBT_PROFILES_DIR }}"
  DBT_VERSION: "${{ vars.DBT_VERSION }}"
  ACCOUNT: "${{ vars.ACCOUNT }}"
  ROLE: "${{ vars.ROLE }}"
  USER: "${{ vars.USER }}"
  PASSWORD: "${{ secrets.PASSWORD }}"
  REGION: "${{ vars.REGION }}"
  DATABASE: "${{ vars.DATABASE }}"
  WAREHOUSE: "${{ vars.WAREHOUSE }}"
  SCHEMA: "${{ vars.SCHEMA }}"

concurrency:
  group: ${{ github.workflow }}

jobs:
  called_workflow_template:
    uses: FlipsideCrypto/analytics-workflow-templates/.github/workflows/dbt_run_template.yml@main
    with:
      dbt_command: >
        dbt run-operation load_blocks_lq; dbt run-operation load_txs_lq ;dbt run -m models/silver/silver__blocks.sql models/silver/silver__transactions.sql+ 
      environment: workflow_prod
      warehouse: ${{ vars.WAREHOUSE }}
    secrets: inherit 
