version: 2

sources:
  - name: crosschain
    database: "{{ 'crosschain' if target.database == 'SEI' else 'crosschain_dev' }}"
    schema: core
    tables:
      - name: dim_date_hours
      - name: dim_dates
      - name: dim_labels
  - name: lq
    database: "{{ 'SEI_TESTNET' if target.database == 'SEI_TESTNET' else 'SEI' }}"
    schema: bronze
    tables:
      - name: lq_blocks
      - name: lq_txs
      - name: lq_txs_101
  - name: bronze_api
    schema: bronze_api
    tables:
      - name: blockchain
  - name: crosschain_silver
    database: "{{ 'crosschain' if target.database == 'SEI' else 'crosschain_dev' }}"
    schema: silver
    tables:
      - name: asset_metadata_coin_market_cap
      - name: asset_metadata_coin_gecko
      - name: hourly_prices_coin_market_cap
      - name: hourly_prices_coin_gecko
      - name: number_sequence
      - name: labels_combined
      - name: complete_native_asset_metadata
      - name: complete_native_prices
      - name: complete_token_asset_metadata
      - name: complete_token_prices
      - name: complete_provider_asset_metadata
      - name: complete_provider_prices
  - name: bronze_streamline
    database: streamline
    schema: |
      {{ "SEI_DEV" if var("STREAMLINE_USE_DEV_FOR_EXTERNAL_TABLES", False) else "SEI" }}
    tables:
      # - name: blocks
      # - name: transactions
      # - name: txcount
      - name: evm_blocks
      - name: evm_transactions
      - name: evm_confirm_blocks
      - name: evm_receipts
      - name: evm_traces
      - name: blocks_v2
      - name: transactions_v2
      - name: txcount_v2
      - name: evm_decoded_logs
      - name: sei_addresses
      - name: evm_blocks_v2
      - name: evm_transactions_v2
      - name: contract_abis
  - name: bronze
    schema: bronze
    tables:
      - name: bridge_wormhole_chain_ids
  - name: axelar_silver
    database: "{{ 'axelar' if target.database == 'SEI' else 'axelar_dev' }}"
    schema: silver
    tables:
      - name: link_events
      - name: transfers
  - name: osmosis
    database: "{{ 'osmosis' if target.database == 'SEI' else 'osmosis_dev' }}"
    schema: silver
    tables:
      - name: asset_metadata
  - name: github_actions
    database: sei
    schema: github_actions
    tables:
      - name: workflows
  - name: external_gold_defillama
    database: external
    schema: defillama
    tables:
      - name: dim_chains
  - name: crosschain_public
    database: crosschain
    schema: bronze_public
    tables:
      - name: user_abis
  - name: silver
    schema: silver
    tables:
      - name: dex_swaps_seaswap
      - name: lp_actions_seaswap
      - name: lp_actions_fuzio
      - name: lp_actions_astroport
  - name: data_science_silver
    database: datascience
    schema: silver
    tables:
      - name: evm_event_sigs
      - name: evm_known_event_names
      - name: evm_known_event_sigs
      - name: evm_wrapped_assets
      - name: dates
      - name: scoring_activity_categories
  - name: abis_silver
    database: "{{ target.database }}"
    schema: silver_evm
    tables:
      - name: verified_abis
      - name: complete_event_abis
  - name: complete_streamline
    database: "{{ target.database }}"
    schema: streamline
    tables:
      - name: complete_contract_abis