version: 2

sources:
  - name: crosschain
    database: "{{ 'crosschain' if target.database == 'SEI' else 'crosschain_dev' }}"
    schema: core
    tables:
      - name: dim_date_hours
      - name: dim_dates
      - name: dim_labels
  - name: lq
    database: "{{ 'SEI_TESTNET' if target.database == 'SEI_TESTNET' else 'SEI' }}"
    schema: bronze
    tables:
      - name: lq_blocks
      - name: lq_txs
      - name: lq_txs_101
  - name: bronze_api
    schema: bronze_api
    tables:
      - name: blockchain
  - name: crosschain_silver
    database: "{{ 'crosschain' if target.database == 'SEI' else 'crosschain_dev' }}"
    schema: silver
    tables:
      - name: asset_metadata_coin_market_cap
      - name: asset_metadata_coin_gecko
      - name: hourly_prices_coin_market_cap
      - name: hourly_prices_coin_gecko
      - name: number_sequence
  - name: bronze_streamline
    database: streamline
    schema: |
      {{ "SEI_DEV" if var("STREAMLINE_USE_DEV_FOR_EXTERNAL_TABLES", False) else "SEI" }}
    tables:
      - name: blocks
      - name: transactions
      - name: txcount
  - name: bronze
    schema: bronze
    tables:
      - name: bridge_wormhole_chain_ids
  - name: axelar_silver
    database: "{{ 'axelar' if target.database == 'SEI' else 'axelar_dev' }}"
    schema: silver
    tables:
      - name: link_events
      - name: transfers
  - name: osmosis
    database: "{{ 'osmosis' if target.database == 'SEI' else 'osmosis_dev' }}"
    schema: silver
    tables:
      - name: asset_metadata