version: 2

sources:
  - name: crosschain
    database: "{{ 'crosschain' if target.database == 'SEI' else 'crosschain_dev' }}"
    schema: core
    tables:
      - name: dim_date_hours
      - name: address_tags
      - name: dim_dates
  - name: lq
    database: "{{ 'SEI_TESTNET' if target.database == 'SEI_TESTNET' else 'SEI' }}"
    schema: bronze
    tables:
      - name: lq_blocks
      - name: lq_txs
      - name: lq_txs_101
  - name: crosschain
    database: "{{ 'crosschain_dev' if target.database == 'SEI_DEV' else 'crosschain' }}"
    schema: core
    tables:
      - name: address_labels
  - name: streamline
    database: streamline
    schema:  "{{ 'SEI' if target.database == 'SEI' else 'SEI_DEV' }}"
    tables:
      - name: blocks
      - name: tx_search